"use client";

import { usePathname } from "next/navigation";

import PrivateRoute from "@/shared/components/PrivateRoute";
import { Providers } from "@/shared/contexts";
import { checkIsPublicRoute } from "@/shared/functions/check-is-public-route";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { CssBaseline } from "@mui/material";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isPublicPage = checkIsPublicRoute(pathname);

  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <CssBaseline />
        <Providers>
          {isPublicPage && children}
          {!isPublicPage && <PrivateRoute>{children}</PrivateRoute>}
        </Providers>
      </body>
    </html>
  );
}
